version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
    labels:
      - "dependencies"

  # Python UV
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "pre-commit"
      - dependency-name: "pytest"
      - dependency-name: "pytest-cov"
      - dependency-name: "ruff"
    commit-message:
      prefix: ⬆
    labels:
      - "dependencies"
